"""The bundled SYNTHETIC demonstration dataset (generated by jobs/generate_demo_parcels.py).

Not an official land record — every attribute is fabricated. See DATA.md.
"""

import json
from functools import lru_cache

from .config import DATA_DIR


@lru_cache(maxsize=1)
def load_parcels() -> dict:
    return json.loads((DATA_DIR / "demo-parcels.geojson").read_text("utf-8"))


@lru_cache(maxsize=1)
def load_buildings() -> dict:
    return json.loads((DATA_DIR / "demo-buildings.geojson").read_text("utf-8"))
